# -*- coding: utf-8 -*-
"""dataMining_project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SU17T8bPLajpAtr8M4pWwcIxvBeSFJrj
"""

#!python --version

from __future__ import print_function

# !pip uninstall pandas -y

# !pip install pandas==0.25.1

import pandas as pd
#pd.__version__

# !pip uninstall scikit-learn -y

# !pip install scikit-learn==0.21.2

import sklearn
#sklearn.__version__

import pickle

def isNaN(num):
    return num != num

import datetime 

def dateTimeFunction(date, time):
  month,day,year = dateFunc(date)
  hour,minute,second = timeFunc(time)
  dt = datetime.datetime(int(year),int(month),int(day),int(hour),int(minute),int(second))
  return dt

def dateFunc(date):
  y,m,d = date.split('/')
  return y,m,d

def timeFunc(time):
  h,m,s = time.split(':')
  return h,m,s

def findInsulinTimestamp(df_insulin):
  for i in df_insulin.iterrows():
    if i[1][16] == 'AUTO MODE ACTIVE PLGM OFF':
      dateTime = dateTimeFunction(i[1][1], i[1][2])
      return dateTime 
  return None

def currentDayFunc(d, t):
  currentDay = dateTimeFunction(d, t)
  return currentDay

# Main Function for CS 572 Data Mining Project 1 to find 36 Results

def main(hyperglycemia180, hyperglycemiaCritical250, tupleRange, tupleRangeSecondary, hypoglycemiaThreshold_lvl1_70, hypoglycemiaThreshold_lvl2_54):
  # read in data
  df_insulin = pd.read_csv('InsulinData.csv')
  df_cgm = pd.read_csv('CGMData.csv')
  # df_results = pd.read_csv('Results.csv')
  
  # reverse order of dataframe so time is in chronological order
  df_insulin = df_insulin.iloc[::-1]
  df_cgm = df_cgm.iloc[::-1]

  # initalize timestamp for switch from manual to auto
  insulin_manualAuto_timestamp = findInsulinTimestamp(df_insulin)
  
  # initialize 36 final vars for results
  hypoglycemia54_manualNumber_day_1_12_final = 0
  hypoglycemia54_manualNumber_night_1_6_final = 0
  hypoglycemia54_autoNumber_day_2_12_final = 0
  hypoglycemia54_autoNumber_night_2_6_final = 0

  hypoglycemia70_manualNumber_day_1_11_final = 0
  hypoglycemia70_manualNumber_night_1_5_final = 0
  hypoglycemia70_autoNumber_day_2_11_final = 0
  hypoglycemia70_autoNumber_night_2_5_final = 0

  hypoglycemia54_manual_total_1_18_final = 0 
  hypoglycemia54_auto_total__2_18_final = 0 

  hypoglycemia70_manual_total_1_17_final = 0 
  hypoglycemia70_auto_total_2_17_final = 0 

  hyperglycemia180_manual_day_1_7_final = 0
  hyperglycemia180_manual_night_1_1_final = 0
  hyperglycemia180_manual_total_1_13_final = 0

  hyperglycemia180_auto_day_2_7_final = 0
  hyperglycemia180_auto_night_2_1_final = 0
  hyperglycemia180_auto_total_2_13_final = 0

  hyperglycemia250_manual_day_1_8_final = 0
  hyperglycemia250_manual_night_1_2_final = 0
  hyperglycemia250_manual_total_1_14_final = 0

  hyperglycemia250_auto_day_2_8_final = 0
  hyperglycemia250_auto_night_2_2_final = 0
  hyperglycemia250_auto_total_2_14_final = 0


  range1_manual_day_1_9_final = 0
  range1_manual_night_1_3_final = 0
  range1_manual_total_1_15_final = 0

  range1_auto_day_2_9_final = 0
  range1_auto_night_2_3_final = 0
  range1_auto_total_2_15_final = 0

  range2_manual_day_1_10_final = 0
  range2_manual_night_1_4_final = 0
  range2_manual_total_1_16_final = 0

  range2_auto_day_2_10_final = 0
  range2_auto_night_2_4_final = 0
  range2_auto_total_2_16_final = 0


  # counter for num days
  numDaysManual = 0 
  numDaysAuto = 0

  # initialize current date
  currentDay = currentDayFunc(df_cgm.iloc[0][1], df_cgm.iloc[0][2])

  # initalize counters

  hypoglycemia54_manualNumber_day_1_12 = 0
  hypoglycemia54_manualNumber_night_1_6 = 0
  hypoglycemia54_autoNumber_day_2_12 = 0
  hypoglycemia54_autoNumber_night_2_6 = 0

  hypoglycemia70_manualNumber_day_1_11 = 0
  hypoglycemia70_manualNumber_night_1_5 = 0
  hypoglycemia70_autoNumber_day_2_11 = 0
  hypoglycemia70_autoNumber_night_2_5 = 0

  hypoglycemia54_manual_total_1_18 = 0 
  hypoglycemia54_auto_total__2_18 = 0 

  hypoglycemia70_manual_total_1_17 = 0 
  hypoglycemia70_auto_total_2_17 = 0 

  hyperglycemia180_manual_day_1_7 = 0
  hyperglycemia180_manual_night_1_1 = 0
  hyperglycemia180_manual_total_1_13 = 0

  hyperglycemia180_auto_day_2_7 = 0
  hyperglycemia180_auto_night_2_1 = 0
  hyperglycemia180_auto_total_2_13 = 0

  hyperglycemia250_manual_day_1_8 = 0
  hyperglycemia250_manual_night_1_2 = 0
  hyperglycemia250_manual_total_1_14 = 0

  hyperglycemia250_auto_day_2_8 = 0
  hyperglycemia250_auto_night_2_2 = 0
  hyperglycemia250_auto_total_2_14 = 0

  range1_manual_day_1_9 = 0
  range1_manual_night_1_3 = 0
  range1_manual_total_1_15 = 0

  range1_auto_day_2_9 = 0
  range1_auto_night_2_3 = 0
  range1_auto_total_2_15 = 0

  range2_manual_day_1_10 = 0
  range2_manual_night_1_4 = 0
  range2_manual_total_1_16 = 0

  range2_auto_day_2_10 = 0
  range2_auto_night_2_4 = 0
  range2_auto_total_2_16 = 0

  # main for loop
  for i in df_cgm.iterrows():
    date = i[1][1]
    time = i[1][2]
    dateTime = dateTimeFunction(i[1][1], i[1][2])

    cgm_raw = i[1][30]

    if isNaN(cgm_raw):
      continue

    cgm = float(cgm_raw)    

    midnight_start = datetime.datetime(dateTime.year, dateTime.month, dateTime.day, 0,0,0) 
    sixAM = datetime.datetime(dateTime.year, dateTime.month, dateTime.day, 6,0,0)
    midnight_end = datetime.datetime(dateTime.year, dateTime.month, dateTime.day, 0,0,0) + datetime.timedelta(days=1)

    if currentDay.date() != dateTime.date() and currentDay <= insulin_manualAuto_timestamp: 
      numDaysManual += 1
    elif currentDay.date() != dateTime.date():
      numDaysAuto += 1
    

    if currentDay.date() != dateTime.date():
      # add day's worth of metrics to final vars
      hypoglycemia54_manualNumber_day_1_12_final += hypoglycemia54_manualNumber_day_1_12 / 288
      hypoglycemia54_manualNumber_night_1_6_final += hypoglycemia54_manualNumber_night_1_6 / 288
      hypoglycemia54_autoNumber_day_2_12_final +=  hypoglycemia54_autoNumber_day_2_12 / 288
      hypoglycemia54_autoNumber_night_2_6_final += hypoglycemia54_autoNumber_night_2_6 / 288

      hypoglycemia70_manualNumber_day_1_11_final += hypoglycemia70_manualNumber_day_1_11 / 288
      hypoglycemia70_manualNumber_night_1_5_final += hypoglycemia70_manualNumber_night_1_5 / 288
      hypoglycemia70_autoNumber_day_2_11_final += hypoglycemia70_autoNumber_day_2_11 / 288
      hypoglycemia70_autoNumber_night_2_5_final += hypoglycemia70_autoNumber_night_2_5 / 288

      hypoglycemia54_manual_total_1_18_final += hypoglycemia54_manual_total_1_18 / 288
      hypoglycemia54_auto_total__2_18_final += hypoglycemia54_auto_total__2_18 / 288

      hypoglycemia70_manual_total_1_17_final += hypoglycemia70_manual_total_1_17 / 288
      hypoglycemia70_auto_total_2_17_final += hypoglycemia70_auto_total_2_17 / 288

      hyperglycemia180_manual_day_1_7_final += hyperglycemia180_manual_day_1_7 / 288
      hyperglycemia180_manual_night_1_1_final += hyperglycemia180_manual_night_1_1 / 288
      hyperglycemia180_manual_total_1_13_final += hyperglycemia180_manual_total_1_13 / 288

      hyperglycemia180_auto_day_2_7_final += hyperglycemia180_auto_day_2_7 / 288
      hyperglycemia180_auto_night_2_1_final += hyperglycemia180_auto_night_2_1 / 288
      hyperglycemia180_auto_total_2_13_final += hyperglycemia180_auto_total_2_13 / 288

      hyperglycemia250_manual_day_1_8_final += hyperglycemia250_manual_day_1_8 / 288
      hyperglycemia250_manual_night_1_2_final += hyperglycemia250_manual_night_1_2 / 288
      hyperglycemia250_manual_total_1_14_final += hyperglycemia250_manual_total_1_14 / 288

      hyperglycemia250_auto_day_2_8_final += hyperglycemia250_auto_day_2_8 / 288
      hyperglycemia250_auto_night_2_2_final += hyperglycemia250_auto_night_2_2 / 288
      hyperglycemia250_auto_total_2_14_final += hyperglycemia250_auto_total_2_14 / 288

      range1_manual_day_1_9_final += range1_manual_day_1_9 / 288
      range1_manual_night_1_3_final += range1_manual_night_1_3 / 288
      range1_manual_total_1_15_final += range1_manual_total_1_15 / 288

      range1_auto_day_2_9_final += range1_auto_day_2_9 / 288
      range1_auto_night_2_3_final += range1_auto_night_2_3 / 288
      range1_auto_total_2_15_final += range1_auto_total_2_15 / 288

      range2_manual_day_1_10_final += range2_manual_day_1_10 / 288
      range2_manual_night_1_4_final += range2_manual_night_1_4 / 288
      range2_manual_total_1_16_final += range2_manual_total_1_16 / 288

      range2_auto_day_2_10_final += range2_auto_day_2_10 / 288
      range2_auto_night_2_4_final += range2_auto_night_2_4 / 288
      range2_auto_total_2_16_final += range2_auto_total_2_16 / 288
      #
      # set counters back to 0
      #
      hypoglycemia54_manualNumber_day_1_12 = 0
      hypoglycemia54_manualNumber_night_1_6 = 0
      hypoglycemia54_autoNumber_day_2_12 = 0
      hypoglycemia54_autoNumber_night_2_6 = 0

      hypoglycemia70_manualNumber_day_1_11 = 0
      hypoglycemia70_manualNumber_night_1_5 = 0
      hypoglycemia70_autoNumber_day_2_11 = 0
      hypoglycemia70_autoNumber_night_2_5 = 0

      hypoglycemia54_manual_total_1_18 = 0 
      hypoglycemia54_auto_total__2_18 = 0 

      hypoglycemia70_manual_total_1_17 = 0 
      hypoglycemia70_auto_total_2_17 = 0 

      hyperglycemia180_manual_day_1_7 = 0
      hyperglycemia180_manual_night_1_1 = 0
      hyperglycemia180_manual_total_1_13 = 0

      hyperglycemia180_auto_day_2_7 = 0
      hyperglycemia180_auto_night_2_1 = 0
      hyperglycemia180_auto_total_2_13 = 0

      hyperglycemia250_manual_day_1_8 = 0
      hyperglycemia250_manual_night_1_2 = 0
      hyperglycemia250_manual_total_1_14 = 0

      hyperglycemia250_auto_day_2_8 = 0
      hyperglycemia250_auto_night_2_2 = 0
      hyperglycemia250_auto_total_2_14 = 0

      range1_manual_day_1_9 = 0
      range1_manual_night_1_3 = 0
      range1_manual_total_1_15 = 0

      range1_auto_day_2_9 = 0
      range1_auto_night_2_3 = 0
      range1_auto_total_2_15 = 0

      range2_manual_day_1_10 = 0
      range2_manual_night_1_4 = 0
      range2_manual_total_1_16 = 0

      range2_auto_day_2_10 = 0
      range2_auto_night_2_4 = 0
      range2_auto_total_2_16 = 0

    
    
    if dateTime <= insulin_manualAuto_timestamp:
      # manual
      if sixAM <= dateTime and dateTime < midnight_end:
        # day
        if cgm < hypoglycemiaThreshold_lvl2_54:
          hypoglycemia54_manualNumber_day_1_12 += 1
          hypoglycemia54_manual_total_1_18 += 1
          
        if cgm < hypoglycemiaThreshold_lvl1_70 and cgm >= hypoglycemiaThreshold_lvl2_54:
          hypoglycemia70_manualNumber_day_1_11 += 1
          hypoglycemia70_manual_total_1_17 += 1
        
        if cgm > hyperglycemia180 and cgm <= hyperglycemiaCritical250:
          hyperglycemia180_manual_day_1_7 += 1
          hyperglycemia180_manual_total_1_13 += 1

        if cgm > hyperglycemiaCritical250:
          hyperglycemia250_manual_day_1_8 += 1 
          hyperglycemia250_manual_total_1_14 += 1

        if cgm >= tupleRange[0] and cgm <= tupleRange[1]:
          range1_manual_day_1_9 += 1
          range1_manual_total_1_15 += 1
        
        if cgm >= tupleRangeSecondary[0] and cgm <= tupleRangeSecondary[1]:
          range2_manual_day_1_10 += 1
          range2_manual_total_1_16 += 1


      elif dateTime < sixAM and dateTime >= midnight_start: 
        # night
        if cgm < hypoglycemiaThreshold_lvl2_54:
          hypoglycemia54_manualNumber_night_1_6 += 1
          hypoglycemia54_manual_total_1_18 += 1

        if cgm < hypoglycemiaThreshold_lvl1_70 and cgm >= hypoglycemiaThreshold_lvl2_54:
          hypoglycemia70_manualNumber_night_1_5 += 1
          hypoglycemia70_manual_total_1_17 += 1

        if cgm > hyperglycemia180 and cgm <= hyperglycemiaCritical250:
          hyperglycemia180_manual_night_1_1 += 1
          hyperglycemia180_manual_total_1_13 += 1

        if cgm > hyperglycemiaCritical250:
          hyperglycemia250_manual_night_1_2 += 1 
          hyperglycemia250_manual_total_1_14 += 1

        if cgm >= tupleRange[0] and cgm <= tupleRange[1]:
          range1_manual_night_1_3 += 1
          range1_manual_total_1_15 += 1

        if cgm >= tupleRangeSecondary[0] and cgm <= tupleRangeSecondary[1]:
          range2_manual_night_1_4 += 1
          range2_manual_total_1_16 += 1

    else:
      # auto
      if sixAM <= dateTime and dateTime < midnight_end:
        # day
        if cgm < hypoglycemiaThreshold_lvl2_54:
          hypoglycemia54_autoNumber_day_2_12 += 1
          hypoglycemia54_auto_total__2_18 += 1

        if cgm < hypoglycemiaThreshold_lvl1_70 and cgm >= hypoglycemiaThreshold_lvl2_54:
          hypoglycemia70_autoNumber_day_2_11 += 1
          hypoglycemia70_auto_total_2_17 += 1

        if cgm > hyperglycemia180 and cgm <= hyperglycemiaCritical250:
          hyperglycemia180_auto_day_2_7 += 1
          hyperglycemia180_auto_total_2_13 += 1

        if cgm > hyperglycemiaCritical250:
          hyperglycemia250_auto_day_2_8 += 1
          hyperglycemia250_auto_total_2_14 += 1

        if cgm >= tupleRange[0] and cgm <= tupleRange[1]:
          range1_auto_day_2_9 += 1
          range1_auto_total_2_15 += 1

        if cgm >= tupleRangeSecondary[0] and cgm <= tupleRangeSecondary[1]:
          range2_auto_day_2_10 += 1
          range2_auto_total_2_16 += 1

          
      elif dateTime < sixAM and dateTime >= midnight_start: 
        # night
        if cgm < hypoglycemiaThreshold_lvl2_54:
          hypoglycemia54_autoNumber_night_2_6 += 1
          hypoglycemia54_auto_total__2_18 += 1

        if cgm < hypoglycemiaThreshold_lvl1_70 and cgm >= hypoglycemiaThreshold_lvl2_54:
          hypoglycemia70_autoNumber_night_2_5 += 1
          hypoglycemia70_auto_total_2_17 += 1

        if cgm > hyperglycemia180 and cgm <= hyperglycemiaCritical250:
          hyperglycemia180_auto_night_2_1 += 1
          hyperglycemia180_auto_total_2_13 += 1

        if cgm > hyperglycemiaCritical250:
          hyperglycemia250_auto_night_2_2 += 1
          hyperglycemia250_auto_total_2_14 += 1

        if cgm >= tupleRange[0] and cgm <= tupleRange[1]:
          range1_auto_night_2_3 += 1
          range1_auto_total_2_15 += 1
        
        if cgm >= tupleRangeSecondary[0] and cgm <= tupleRangeSecondary[1]:
          range2_auto_night_2_4 += 1
          range2_auto_total_2_16 += 1
    #update currentDay
    currentDay = dateTime

  # last day cuts off before metric added; last day is auto
  numDaysAuto += 1
  #
  #hypoglycemia54_manualNumber_day_1_12_final += hypoglycemia54_manualNumber_day_1_12 / 288
  #hypoglycemia54_manualNumber_night_1_6_final += hypoglycemia54_manualNumber_night_1_6 / 288
  hypoglycemia54_autoNumber_day_2_12_final +=  hypoglycemia54_autoNumber_day_2_12 / 288
  hypoglycemia54_autoNumber_night_2_6_final += hypoglycemia54_autoNumber_night_2_6 / 288

  #hypoglycemia70_manualNumber_day_1_11_final += hypoglycemia70_manualNumber_day_1_11 / 288
  #hypoglycemia70_manualNumber_night_1_5_final += hypoglycemia70_manualNumber_night_1_5 / 288
  hypoglycemia70_autoNumber_day_2_11_final += hypoglycemia70_autoNumber_day_2_11 / 288
  hypoglycemia70_autoNumber_night_2_5_final += hypoglycemia70_autoNumber_night_2_5 / 288

  #hypoglycemia54_manual_total_1_18_final += hypoglycemia54_manual_total_1_18 / 288
  hypoglycemia54_auto_total__2_18_final += hypoglycemia54_auto_total__2_18 / 288

  #hypoglycemia70_manual_total_1_17_final += hypoglycemia70_manual_total_1_17 / 288
  hypoglycemia70_auto_total_2_17_final += hypoglycemia70_auto_total_2_17 / 288

  #hyperglycemia180_manual_day_1_7_final += hyperglycemia180_manual_day_1_7 / 288
  #hyperglycemia180_manual_night_1_1_final += hyperglycemia180_manual_night_1_1 / 288
  #hyperglycemia180_manual_total_1_13_final += hyperglycemia180_manual_total_1_13 / 288

  hyperglycemia180_auto_day_2_7_final += hyperglycemia180_auto_day_2_7 / 288
  hyperglycemia180_auto_night_2_1_final += hyperglycemia180_auto_night_2_1 / 288
  hyperglycemia180_auto_total_2_13_final += hyperglycemia180_auto_total_2_13 / 288

  # hyperglycemia250_manual_day_1_8_final += hyperglycemia250_manual_day_1_8 / 288
  # hyperglycemia250_manual_night_1_2_final += hyperglycemia250_manual_night_1_2 / 288
  # hyperglycemia250_manual_total_1_14_final += hyperglycemia250_manual_total_1_14 / 288

  hyperglycemia250_auto_day_2_8_final += hyperglycemia250_auto_day_2_8 / 288
  hyperglycemia250_auto_night_2_2_final += hyperglycemia250_auto_night_2_2 / 288
  hyperglycemia250_auto_total_2_14_final += hyperglycemia250_auto_total_2_14 / 288

  # range1_manual_day_1_9_final += range1_manual_day_1_9 / 288
  # range1_manual_night_1_3_final += range1_manual_night_1_3 / 288
  # range1_manual_total_1_15_final += range1_manual_total_1_15 / 288

  range1_auto_day_2_9_final += range1_auto_day_2_9 / 288
  range1_auto_night_2_3_final += range1_auto_night_2_3 / 288
  range1_auto_total_2_15_final += range1_auto_total_2_15 / 288

  # range2_manual_day_1_10_final += range2_manual_day_1_10 / 288
  # range2_manual_night_1_4_final += range2_manual_night_1_4 / 288
  # range2_manual_total_1_16_final += range2_manual_total_1_16 / 288

  range2_auto_day_2_10_final += range2_auto_day_2_10 / 288
  range2_auto_night_2_4_final += range2_auto_night_2_4 / 288
  range2_auto_total_2_16_final += range2_auto_total_2_16 / 288
  #
  # calculate final percentages
  # 
  hypoglycemia54_manualNumber_day_1_12_final = 100 * hypoglycemia54_manualNumber_day_1_12_final / numDaysManual
  hypoglycemia54_manualNumber_night_1_6_final = 100 * hypoglycemia54_manualNumber_night_1_6_final / numDaysManual
  hypoglycemia54_autoNumber_day_2_12_final = 100 * hypoglycemia54_autoNumber_day_2_12_final / numDaysAuto
  hypoglycemia54_autoNumber_night_2_6_final = 100 * hypoglycemia54_autoNumber_night_2_6_final / numDaysAuto

  hypoglycemia70_manualNumber_day_1_11_final = 100 * hypoglycemia70_manualNumber_day_1_11_final / numDaysManual
  hypoglycemia70_manualNumber_night_1_5_final = 100 * hypoglycemia70_manualNumber_night_1_5_final / numDaysManual
  hypoglycemia70_autoNumber_day_2_11_final = 100 * hypoglycemia70_autoNumber_day_2_11_final / numDaysAuto
  hypoglycemia70_autoNumber_night_2_5_final = 100 * hypoglycemia70_autoNumber_night_2_5_final / numDaysAuto

  hypoglycemia54_manual_total_1_18_final = 100 * hypoglycemia54_manual_total_1_18_final / numDaysManual
  hypoglycemia54_auto_total__2_18_final = 100 * hypoglycemia54_auto_total__2_18_final / numDaysAuto

  hypoglycemia70_manual_total_1_17_final = 100 * hypoglycemia70_manual_total_1_17_final / numDaysManual
  hypoglycemia70_auto_total_2_17_final = 100 * hypoglycemia70_auto_total_2_17_final / numDaysAuto

  hyperglycemia180_manual_day_1_7_final = 100 * hyperglycemia180_manual_day_1_7_final / numDaysManual
  hyperglycemia180_manual_night_1_1_final = 100 * hyperglycemia180_manual_night_1_1_final / numDaysManual
  hyperglycemia180_manual_total_1_13_final = 100 * hyperglycemia180_manual_total_1_13_final / numDaysManual

  hyperglycemia180_auto_day_2_7_final = 100 * hyperglycemia180_auto_day_2_7_final / numDaysAuto
  hyperglycemia180_auto_night_2_1_final = 100 * hyperglycemia180_auto_night_2_1_final / numDaysAuto
  hyperglycemia180_auto_total_2_13_final = 100 * hyperglycemia180_auto_total_2_13_final / numDaysAuto

  hyperglycemia250_manual_day_1_8_final = 100 * hyperglycemia250_manual_day_1_8_final / numDaysManual
  hyperglycemia250_manual_night_1_2_final = 100 * hyperglycemia250_manual_night_1_2_final / numDaysManual
  hyperglycemia250_manual_total_1_14_final = 100 * hyperglycemia250_manual_total_1_14_final / numDaysManual

  hyperglycemia250_auto_day_2_8_final = 100 * hyperglycemia250_auto_day_2_8_final / numDaysAuto
  hyperglycemia250_auto_night_2_2_final = 100 * hyperglycemia250_auto_night_2_2_final / numDaysAuto
  hyperglycemia250_auto_total_2_14_final = 100 * hyperglycemia250_auto_total_2_14_final / numDaysAuto

  range1_manual_day_1_9_final = 100 * range1_manual_day_1_9_final / numDaysManual
  range1_manual_night_1_3_final = 100 * range1_manual_night_1_3_final / numDaysManual
  range1_manual_total_1_15_final = 100 * range1_manual_total_1_15_final / numDaysManual

  range1_auto_day_2_9_final = 100 * range1_auto_day_2_9_final / numDaysAuto
  range1_auto_night_2_3_final = 100 * range1_auto_night_2_3_final / numDaysAuto
  range1_auto_total_2_15_final = 100 * range1_auto_total_2_15_final / numDaysAuto

  range2_manual_day_1_10_final = 100 * range2_manual_day_1_10_final / numDaysManual
  range2_manual_night_1_4_final = 100 * range2_manual_night_1_4_final / numDaysManual
  range2_manual_total_1_16_final = 100 * range2_manual_total_1_16_final / numDaysManual

  range2_auto_day_2_10_final = 100 * range2_auto_day_2_10_final / numDaysAuto
  range2_auto_night_2_4_final = 100 * range2_auto_night_2_4_final / numDaysAuto
  range2_auto_total_2_16_final = 100 * range2_auto_total_2_16_final / numDaysAuto
  
  
  results = [[hyperglycemia180_manual_night_1_1_final,hyperglycemia250_manual_night_1_2_final,range1_manual_night_1_3_final,range2_manual_night_1_4_final,hypoglycemia70_manualNumber_night_1_5_final,hypoglycemia54_manualNumber_night_1_6_final,hyperglycemia180_manual_day_1_7_final,hyperglycemia250_manual_day_1_8_final,range1_manual_day_1_9_final,range2_manual_day_1_10_final,hypoglycemia70_manualNumber_day_1_11_final,hypoglycemia54_manualNumber_day_1_12_final,hyperglycemia180_manual_total_1_13_final,hyperglycemia250_manual_total_1_14_final,range1_manual_total_1_15_final,range2_manual_total_1_16_final,hypoglycemia70_manual_total_1_17_final, hypoglycemia54_manual_total_1_18_final],
             [hyperglycemia180_auto_night_2_1_final,hyperglycemia250_auto_night_2_2_final,range1_auto_night_2_3_final,range2_auto_night_2_4_final,hypoglycemia70_autoNumber_night_2_5_final,hypoglycemia54_autoNumber_night_2_6_final,hyperglycemia180_auto_day_2_7_final,hyperglycemia250_auto_day_2_8_final,range1_auto_day_2_9_final,range2_auto_day_2_10_final,hypoglycemia70_autoNumber_day_2_11_final,hypoglycemia54_autoNumber_day_2_12_final,hyperglycemia180_auto_total_2_13_final,hyperglycemia250_auto_total_2_14_final,range1_auto_total_2_15_final,range2_auto_total_2_16_final,hypoglycemia70_auto_total_2_17_final, hypoglycemia54_auto_total__2_18_final]]


  results_df = pd.DataFrame(results)
  results_df.to_csv('Results.csv', header=False, index=False)
  
  #print(results[0])
  #print(results[1]) 
  # print(numDaysManual)
  # print(numDaysAuto)
  return results

print(main(180, 250, (70,180), (70,150), 70, 54))

# [3.8194444444444446, 1.0185185185185186, 18.24074074074074, 13.402777777777777, 0.6712962962962963, 0.0, 15.324074074074074, 9.027777777777777, 37.152777777777786, 28.912037037037027, 2.9629629629629632, 1.9212962962962963, 19.143518518518523, 10.046296296296296, 55.39351851851851, 42.31481481481481, 3.6342592592592595, 1.9212962962962963]
# [2.170138888888889, 0.4012345679012345, 20.04050925925927, 17.484567901234566, 0.4726080246913581, 0.1504629629629629, 14.97492283950617, 4.560185185185187, 45.11574074074071, 33.800154320987666, 2.336033950617285, 0.9837962962962962, 17.145061728395067, 4.96141975308642, 65.15625000000001, 51.28472222222224, 2.808641975308641, 1.1342592592592593]









